### PR TITLE
Feature/rissa

### PR DESCRIPTION
**Pull request by RissaC2**
Its plain but will change to desired colours and add logo....

### CODE REVIEW

**Comment by RissaC2** [comment]
added header using react

**Comment by RissaC2** [comment]
updated the files

**Review by DaisyEverard — CHANGES_REQUESTED** [review]
I think it's all good except the entire <header> div (5 lines) need removing from index.html

**Comment by RissaC2** [comment]
corrected index file

**Review by DaisyEverard — APPROVED** [review]

**Pull request merged**
